before_script:
  - sudo apt-get install rrdtool librrd-dev libxml2-dev libxslt1-dev librrd-ruby -y
  - bundle install

language: ruby

rvm:
  - 1.9.2

script: bundle exec rake spec

notifications:
  email:
    - tim.miller.0@gmail.com
